services:
    php:
        image: php:8.3-apache
        container_name: introsql_php8_3
        ports:
            - "8001:80" # on définit le port pour accéder à l'application (localhost:8001)
        volumes:
            - ./php:/var/www/html # on monte le dossier courant dans le dossier /var/www/html du container
        build:
            context: .
            dockerfile: Dockerfile
    db:
        image: mysql:8.0
        container_name: introsql_mysql8_0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: introsql
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - "./db:/docker-entrypoint-initdb.d" # création de la table et insertion des données à partir du fichier users.sql
        ports:
            - "3307:3306"
    phpma:
        image: phpmyadmin/phpmyadmin
        container_name: introsql_phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 20M
        ports:
            - "8081:80" # on définit le port pour accéder à phpmyadmin (localhost:8081)
